# Gestión de los Recursos Técnicos
|TIPO DE RECURSOS|DESCRIPCIÓN DE RECURSOS|INDICADORES DE USO|
|---|---|---|
|Biblioteca|Textos de consulta, diccionarios enciclopédicos, textos escolares, obras literarias, obras de literatura infantil, revistas Material audiovisual CD. de música.|-Número de estudiantes que utilizan el servicio durante la jornada académica. - Número de usuarios que utilizan el servicio en jornada extraescolar. -Control de préstamo de los textos didácticos (de cada asignatura), bibliográfico, audiovisual y material didáctico a los docentes (a largo y mediano plazo). - Control de préstamo bibliográfico a los estudiantes. -Número de actividades y programas dirigidos por la bibliotecaria a los estudiantes. -Procedimiento y control para sancionar a usuarios que infrinjan el reglamento (Actas y formatos de procedimiento). -Registro diario de préstamo de material. -Formato de inventario actualizado. -Auditorías internas realizadas (Seguimiento y control).|
|Laboratorio de Ciencias Naturales|Equipos de vidrio, equipos de medición, reactivos y material didáctico|-Número de prácticas desarrolladas por periodo académico para complementar las temáticas de aula. -Relación de instrumentos del laboratorio con el número de estudiantes. -Estado de los elementos del laboratorio (bueno, regular, malo) -Estado de los equipos disponibles para las prácticas (bueno, regular, malo) -Formato actualizado de inventario. -Relación de insumos fungibles y control de vencimiento de éstos. -Existencia de reglamento interno. -Auditorías internas realizadas (Seguimiento y control).|
|Telecentro|Equipos de cómputo Estabilizadores Televisor Rack|-Cantidad de personas que utilizan este servicio diariamente. -Reglamento interno de la sala. -Uso que le da el beneficiario al telecentro. (capacitación, uso de internet).|
|Sala de Sistemas|-Equipos de cómputo Estabilizadores Impresora Televisor Rack|-Control de usuarios de la sala. -Control de manejo adecuado de los equipos y sus cuidados. -Existencia de reglamento interno. -Disponibilidad de software específico (paquete de Office) -Disponibilidad de la sala para el manejo de las TICS. (Manejo de horario). -Mantenimiento preventivo de software y hardware. - Auditorías internas realizadas (Seguimiento y control). -Formato actualizado de inventario.|
|Computadores para el Área Administrativa|Un computador por sede|-Estado de los computadores (bueno, regular, malo) -Personas que utilizan los computadores (docentes, directivos). -Finalidad de estos equipos.|
|Auditorio (Sala de Proyecciones)|Sillas. Mesa de auditorio. Atril Banderas. Astas Pantalla|-Actividades en las que se utiliza este espacio (actos culturales, reuniones de padres de familia, proyecciones de las diferentes áreas, actividades pedagógicas e interinstitucionales, reuniones estudiantiles, conferencias y talleres). -Número de actividades realizadas por periodo académico -Reglamento de utilización y conservación del espacio.|
|Audiovisuales|Portátiles Video bean Televisores DVD Grabadoras|-Actividades en las que se utilizan estos recursos (clases, actos culturales, socializaciones, reuniones) -Frecuencia con la que son utilizados (diario, semanal o mensual) -Estado de los equipos (bueno, regular, malo). -Existencia de manual de funcionamiento. -Control de préstamo.|
|Material Deportivo|Implementos deportivos fungibles y no fungibles|-Existencia de control de manejo de préstamo. -Número de elementos en relación al número de estudiantes. -Estado de los elementos (bueno, regular, malo). -Control de inventario actualizado. -Frecuencia de uso del material (diario, semanal, mensual). -Uso de los implementos deportivos en tiempo extracurricular.|
|Sala de materiales y recursos de apoyo pedagógico|Mapas Carteles y afiches Instrumentos musicales Trajes para danzas Juegos de mesa|-Espacio físico (suficiente, insuficiente, inadecuado, adecuado, iluminado, poco iluminado) -Actualización de inventario de los materiales ubicados en esta dependencia. -Clasificación de estos materiales. -Estado de estos materiales (bueno, regular, malo) -Frecuencia de uso de estos materiales (semanal, mensual). -Existencia de formato de control de préstamo de los materiales.|
: Gestión de los Recursos Técnicos {.responsive #tbl-recursos-tecnicos}
