# Servicios Complementarios
<div class="table-responsive">
<table>
<colgroup>
<col />
<col />
</colgroup>
<thead>
<tr>
<th colspan="2"><strong>PORTAFOLIO INSTITUCIONAL</strong></th>
</tr>
</thead>
<tbody>
<tr>
<td><strong>SERVICIOS</strong></td>
<td><strong>DESCRIPCIÓN Y CRITERIOS DE IMPLEMENTACIÓN</strong></td>
</tr>
<tr>
<td>Restaurante</td>
<td>Servicio prestado por el consorcio Salud Sana, contratado desde la alcaldía, beneficia a los niños que deseen hacer uso de éste, cancelando semanalmente una cuota de recuperación estipulada desde la alcaldía. A los niños que no cancelan, se les subsidia este servicio en un 100%</td>
</tr>
<tr>
<td>Cafetería</td>
<td>Funciona en la sede central ofreciendo los servicios de comestibles para los estudiantes y docentes. En las sedes de primaria funcionan casetas atendidas por personas de la comunidad ofreciendo principalmente dulcería y algunos comestibles.</td>
</tr>
<tr>
<td>Transporte</td>
<td>Es contratado por la institución educativa y pagado con los fondos que se reciben específicamente para tal fin. Los estudiantes transportados son los que provienen del área rural próxima al colegio (Vereda las Palomas)</td>
</tr>
<tr>
<td>Telecentro</td>
<td>Funciona en la sede Ricardo Flórez constituyéndose en un servicio de extensión a la comunidad que beneficia potencialmente a toda la población de los barrios cercanos (Viveros, Minitas, La toscana Villa Luz y Villa Café).</td>
</tr>
<tr>
<td>Préstamo de Espacios Físicos</td>
<td>Las instalaciones de la institución son prestadas a las personas de la comunidad y/o entidades que requieran de estas con el fin de realizar actividades en beneficio de nuestra comunidad</td>
</tr>
</tbody>
</table>
</div>
: Servicios Complementarios {.responsive #tbl-servicios-complementarios}
