# ⚙️ Protocolo de Operacionalización de la Vida Estudiantil

## Liderazgo Estudiantil

La vida escolar de la institución gravita en torno al surgimiento y validación de las propuestas de los educandos. Para incentivar este proceso integral y dinámico, se garantiza la articulación permanente entre las coordinaciones y los representantes en espacios como los juegos interclases e intercolegiados, las salidas de campo, las izadas de bandera, los proyectos culturales y la celebración de jornadas institucionales especiales.

## Veeduría del Consejo de Padres

Bajo el acompañamiento técnico del área de Ciencias Sociales, este órgano del gobierno escolar sesionará de forma periódica con el fin de auditar que los derechos y deberes de la comunidad no sean vulnerados. Actuará además como el principal puente comunicativo ante la implementación de reformas curriculares o adecuaciones metodológicas (como la Jornada Única) que requieran socialización y clarificación pedagógica con las familias.

> **EQUIPO DE CALIDAD 2026**
