# DISEÑO CURRICULAR

El diseño curricular de la Institución Educativa Mariscal Sucre se fundamenta en su misión y visión, así como en el Modelo Pedagógico "Educar para Transformar". Este diseño busca ofrecer una formación integral que desarrolle competencias académicas, sociales, emocionales y tecnológicas en los estudiantes, preparándolos para enfrentar los desafíos del mundo actual. A continuación, se presenta el diseño curricular dividido en varios componentes clave.

**Tabla 26**
*Matriz Técnica del Diseño Curricular Integrado*

|Componente Curricular|Ejes y Asignaturas Articuladas|Enfoque Pedagógico y Competencias|Estrategia de Aula y Flexibilidad (EAU)|Evaluación e Integración Comunitaria|
|---|---|---|---|---|
|🏢 1. Fundamentos y Contexto|• Alineación con Misión, Visión y Principios.  • Entorno social de Manizales.|• Inclusión y equidad.  • Respeto por la diversidad y desarrollo sostenible.|• Currículo flexible adaptado a realidades y dinámicas socioeconómicas.|• Monitoreo de necesidades mediante retroalimentación de la comunidad.|
|🧠 2. Eje Cognitivo|• Matemáticas, Ciencias Naturales, Sociales, Castellano, Inglés y Artística.|• Competencias Académicas: Pensamiento crítico, lógico, creativo y habilidades investigativas.|• Aprendizaje Basado en Proyectos (ABP) interdisciplinares y contextualizados.|• Evaluación diagnóstica de período.  • Pruebas sumativas por ciclo.|
|❤️ 3. Eje Socioemocional|• Educación en Valores, Educación Física y Salud, y Orientación.|• Competencias Socioemocionales: Autoconocimiento, autogestión, empatía y trabajo cooperativo.|• Metodologías activas (debates, simulaciones) y seguimiento diario con el "emociómetro".|• Evaluación formativa continua.  • Rúbricas analíticas de convivencia.|
|💻 4. Eje Tecnológico|• Tecnología e Informática, Robótica y Programación.|• Competencias Tecnológicas: Pensamiento computacional, uso crítico de TIC y autonomía digital.|• Integración de tecnologías educativas (EdTech) y laboratorios prácticos en aula.|• Tránsito con "La Universidad en tu Colegio".  • Portafolio de proyectos.|
|🕊️ 5. Eje de Formación Ciudadana|• Educación Cívica y Ética, y Educación Ambiental.|• Competencias Ciudadanas: Conciencia social/ambiental, inclusión y participación comunitaria.|• Educación experiencial, salidas de campo y articulación de las guías de la EAU con el PRAE.|• Proyectos de servicio social obligatorio.  • Alianzas con organizaciones locales.|
: {.responsive}

**Tabla 27**
*Plan de Estudios de Preescolar, Básica Primaria, Secundaria y Media*

<div class="table-responsive">
<table>
<colgroup>
<col />
<col />
<col />
<col />
<col />
<col />
<col />
</colgroup>
<thead>
<tr>
<th colspan="2"><strong>TRANSICIÓN</strong></th>
<th colspan="4"><strong>B Á S I C A P R I MA R I A</strong></th>
<th></th>
</tr>
</thead>
<tbody>
<tr>
<td><strong> </strong></td>
<td><strong>HORAS </strong></td>
<td><strong>1º A 2º </strong></td>
<td><strong>  HORAS</strong></td>
<td><strong>3º A 5º </strong></td>
<td><strong>HORAS </strong></td>
<td></td>
</tr>
<tr>
<td>dimensión comunicativa</td>
<td>6</td>
<td>Castellano</td>
<td>8</td>
<td>Castellano-Inglés</td>
<td>8</td>
<td></td>
</tr>
<tr>
<td>dimensión cognitiva</td>
<td>7</td>
<td rowspan="3"></td>
<td rowspan="3"></td>
<td rowspan="3"></td>
<td rowspan="3"></td>
<td></td>
</tr>
<tr>
<td>dimensión estética</td>
<td>3</td>
<td></td>
</tr>
<tr>
<td>dimensión actitudinal</td>
<td>4</td>
<td></td>
</tr>
<tr>
<td>dimensión corporal y lúdica</td>
<td rowspan="10"><p>5</p>
<p> </p>
<p> </p>
<p> </p>
<p> </p>
<p> </p>
<p> </p></td>
<td>Matemáticas</td>
<td>6</td>
<td>Matemáticas</td>
<td>6</td>
<td></td>
</tr>
<tr>
<td></td>
<td>historia y geografía</td>
<td>2</td>
<td>ciencias sociales</td>
<td>3</td>
<td></td>
</tr>
<tr>
<td></td>
<td>Educaciòn Ambiental</td>
<td>1</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td rowspan="7"><p> </p>
<p> </p>
<p> </p>
<p> </p>
<p> </p>
<p> </p></td>
<td>cívica y urbanidad</td>
<td>1</td>
<td>cívica y urbanidad</td>
<td></td>
<td></td>
</tr>
<tr>
<td>educación religiosa</td>
<td>1</td>
<td>educación religiosa</td>
<td>1</td>
<td></td>
</tr>
<tr>
<td>ciencias naturales</td>
<td>4</td>
<td>ciencias naturales</td>
<td>4</td>
<td></td>
</tr>
<tr>
<td>educación artística</td>
<td>1</td>
<td>educación artística</td>
<td>1</td>
<td></td>
</tr>
<tr>
<td>ética y valores</td>
<td>1</td>
<td>ética y valores</td>
<td>1</td>
<td></td>
</tr>
<tr>
<td>tecnología e informática</td>
<td>2</td>
<td>tecnología e informática</td>
<td>2</td>
<td></td>
</tr>
<tr>
<td>educación física</td>
<td>3</td>
<td>educación física</td>
<td>3</td>
<td></td>
</tr>
<tr>
<td><strong> Total</strong></td>
<td><strong>25</strong></td>
<td> </td>
<td><strong>30</strong></td>
<td> </td>
<td><strong>30</strong></td>
<td></td>
</tr>
<tr>
<td colspan="2"> <strong>BÁSICA SECUNDARIA</strong></td>
<td colspan="3"><p> </p>
<p><strong>MEDIA</strong></p></td>
<td> </td>
<td></td>
</tr>
<tr>
<td><strong>6º a 9º</strong></td>
<td><strong>horas</strong></td>
<td><strong>10º</strong></td>
<td><strong>horas</strong></td>
<td><strong>11º</strong></td>
<td><strong>Horas</strong></td>
<td></td>
</tr>
<tr>
<td>Matemáticas</td>
<td>5</td>
<td>Matemáticas</td>
<td>5</td>
<td>matemáticas</td>
<td>5</td>
<td></td>
</tr>
<tr>
<td>Castellano</td>
<td>6</td>
<td>Castellano</td>
<td>6</td>
<td>castellano</td>
<td>6</td>
<td></td>
</tr>
<tr>
<td>Inglés</td>
<td>4</td>
<td>Inglés</td>
<td>4</td>
<td>inglés</td>
<td>4</td>
<td></td>
</tr>
<tr>
<td>ciencias naturales</td>
<td>5</td>
<td>física y química</td>
<td>6</td>
<td>física y química</td>
<td>6</td>
<td></td>
</tr>
<tr>
<td>educación religiosa</td>
<td>1</td>
<td>educación religiosa</td>
<td>1</td>
<td>educación religiosa</td>
<td>1</td>
<td></td>
</tr>
<tr>
<td>ética y valores</td>
<td>1</td>
<td>ética y valores</td>
<td>1</td>
<td>ética y valores</td>
<td>1</td>
<td></td>
</tr>
<tr>
<td>educación artística</td>
<td>2</td>
<td>educación artística</td>
<td>2</td>
<td>educación artística</td>
<td>1</td>
<td></td>
</tr>
<tr>
<td>tecnología e informática</td>
<td>3</td>
<td>tecnología e informática</td>
<td>3</td>
<td>tecnología e informática</td>
<td>3</td>
<td></td>
</tr>
<tr>
<td>educación física</td>
<td>2</td>
<td>educación física</td>
<td>2</td>
<td>educación física</td>
<td>2</td>
<td></td>
</tr>
<tr>
<td>historia y geografía</td>
<td>5</td>
<td>Economía</td>
<td>2</td>
<td>economía</td>
<td>2</td>
<td></td>
</tr>
<tr>
<td></td>
<td></td>
<td>Filosofía</td>
<td>2</td>
<td>filosofía</td>
<td>2</td>
<td></td>
</tr>
<tr>
<td><mark>emprendimiento</mark></td>
<td><mark>1</mark></td>
<td></td>
<td>1</td>
<td></td>
<td>1</td>
<td></td>
</tr>
<tr>
<td>Educación Ambiental (ecología y medio ambiente)</td>
<td></td>
<td>Educación Ambiental (ecología y medio ambiente)</td>
<td></td>
<td>Educación Ambiental (ecología y medio ambiente)</td>
<td></td>
<td></td>
</tr>
<tr>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td><strong>TOTAL</strong></td>
<td><strong>35</strong></td>
<td></td>
<td><strong>35</strong></td>
<td></td>
<td><strong>35</strong></td>
<td></td>
</tr>
</tbody>
</table>
</div>

**Tabla 28**
*Áreas Transversales (Proyectos Pedagógicos Transversales)*

|ÁREAS TRANSVERSALES|BÁSICA PRIMARIA|BÁSICA SECUNDARIA|EDUCACIÓN MEDIA|
|---|---|---|---|
|EDUCACIÓN PARA LA SEXUALIDAD Y CONSTRUCCIÓN DE CIUDADANÍA|Se implementa a través del proyecto “por una sexualidad y construcción de ciudadanía que mejore su estilo y calidad de vida democráticamente”. El proyecto está orientado a la formación en el auto reconocimiento del cuerpo, el respeto por éste y el manejo adecuado de las relaciones interpersonales.|Se implementa a través del proyecto “por una sexualidad y construcción de ciudadanía que mejore su estilo y calidad de vida democráticamente”. El proyecto está orientado a los jóvenes para que identifiquen sus derechos y deberes en el manejo de la sexualidad.|Se implementa a través del proyecto “por una sexualidad y construcción de ciudadanía que mejore su estilo y calidad de vida democráticamente” El proyecto está orientado a los jóvenes para que identifiquen sus derechos y deberes en el manejo de la sexualidad asumiéndola de manera responsable.|
|EDUCACIÓN AMBIENTAL|Se implementa a través del proyecto “por una persona con conciencia ambiental, para la preservación de la institución educativa Mariscal Sucre y su entorno” El proyecto pretende sensibilizar a la comunidad educativa en el tema ambiental desde todos los ámbitos en las diferentes áreas, con el objetivo de tener una visión sistémica del ambiente y fijar espacios donde compartamos ideas y propuestas para contribuir al desarrollo del sentido de pertenencia, preservación y utilización racional de los recursos naturales|Se implementa a través del proyecto “por una persona con conciencia ambiental, para la preservación de la institución educativa Mariscal Sucre y su entorno” El proyecto pretende sensibilizar a la comunidad educativa en el tema ambiental desde todos los ámbitos en las diferentes áreas, con el objetivo de tener una visión sistémica del ambiente y fijar espacios donde compartamos ideas y propuestas para contribuir al desarrollo del sentido de pertenencia, preservación y utilización racional de los recursos naturales|Se implementa a través del proyecto “por una persona con conciencia ambiental, para la preservación de la institución educativa Mariscal Sucre y su entorno” El proyecto pretende sensibilizar a la comunidad educativa en el tema ambiental desde todos los ámbitos en las diferentes áreas, con el objetivo de tener una visión sistémica del ambiente y fijar espacios donde compartamos ideas y propuestas para contribuir al desarrollo del sentido de pertenencia, preservación y utilización racional de los recursos naturales|
|CONSTITUCIÓN, DEMOCRACIA Y DERECHOS HUMANOS|Se implementa a través del proyecto “Gobierno Escolar y Democracia” La institución se propone con este proyecto dar respuesta a algunas problemáticas de la población escolar, principalmente contribuir a la formación de buenos ciudadanos, con capacidad cívica, de liderazgo y de resolución de conflictos; capaces de convivir pacíficamente, adquirir conciencia democrática y participar activamente en el gobierno escolar, para transformar las costumbres políticas del país.|Se implementa a través del proyecto “Gobierno Escolar y Democracia” La institución se propone con este proyecto dar respuesta a algunas problemáticas de la población escolar, principalmente contribuir a la formación de buenos ciudadanos, con capacidad cívica, de liderazgo y de resolución de conflictos; capaces de convivir pacíficamente, adquirir conciencia democrática y participar activamente en el gobierno escolar, para transformar las costumbres políticas del país.|Se implementa a través del proyecto “Gobierno Escolar y Democracia” La institución se propone con este proyecto dar respuesta a algunas problemáticas de la población escolar, principalmente contribuir a la formación de buenos ciudadanos, con capacidad cívica, de liderazgo y de resolución de conflictos; capaces de convivir pacíficamente, adquirir conciencia democrática y participar activamente en el gobierno escolar, para transformar las costumbres políticas del país.|
|USO CREATIVO DEL TIEMPO LIBRE|Se implementa a través del proyecto "aprovechamiento del tiempo libre”. Debido a la necesidad que tienen los niños de realizar actividades significativas en su tiempo libre, se lleva a cabo el presente proyecto, buscando desarrollar desde una concepción pedagógica la parte artística, lúdica, deportiva y cultural. Se busca permear los espacios y tiempos no escolares o escolarizados abriendo las puertas a la proyección e incidiendo en la transformación del entorno ya que, si queremos que el niño utilice bien su tiempo libre, tenemos que formarlo y educarlo para que haga de éste, un espacio que le proporcione elementos para su desarrollo integral, conduciéndolo a adquirir hábitos de vida saludables, que les permitan vislumbrar y construir un proyecto de vida.|Se implementa a través del proyecto "aprovechamiento del tiempo libre”. Se ha diseñado este proyecto para que los jóvenes desde el ámbito pedagógico y con acompañamiento desarrollen la parte artística, lúdica, deportiva y cultural. El propósito es ocupar a los estudiantes en actividades que generen hábitos de vida saludables y disminuir factores de riesgo (drogas, tabaquismo, alcoholismo, violencia y vandalismo y prostitución).|Se implementa a través del proyecto "aprovechamiento del tiempo libre”. Se ha diseñado este proyecto para que los jóvenes desde el ámbito pedagógico y con acompañamiento desarrollen la parte artística, lúdica, deportiva y cultural. El propósito es ocupar a los estudiantes en actividades que generen hábitos de vida saludables y disminuir factores de riesgo (drogas, tabaquismo, alcoholismo, violencia y vandalismo y prostitución).|
|PREVENCIÓN Y ATENCIÓN DE DESASTRES|Se implementa a través del proyecto “Prevención y atención de desastres” El propósito es preservar la vida a través del diagnóstico de los factores de riesgo de cada sección, la definición de las rutas de evacuación, así como los sitios seguros de encuentro. Atender la necesidad de capacitación de Directivos, Docentes, Estudiantes, padres de familia y Empleados a fin de prepararse a nivel interno para afrontar las amenazas propias en el ámbito locativo o externo, sea natural o entrópico.|Se implementa a través del proyecto “Prevención y atención de desastres” El propósito es preservar la vida a través del diagnóstico de los factores de riesgo de cada sección, la definición de las rutas de evacuación, así como los sitios seguros de encuentro. Atender la necesidad de capacitación de Directivos, Docentes, Estudiantes, padres de familia y Empleados a fin de prepararse a nivel interno para afrontar las amenazas propias en el ámbito locativo o externo, sea natural o entrópico.|Se implementa a través del proyecto “Prevención y atención de desastres” El propósito es preservar la vida a través del diagnóstico de los factores de riesgo de cada sección, la definición de las rutas de evacuación, así como los sitios seguros de encuentro. Atender la necesidad de capacitación de Directivos, Docentes, Estudiantes, padres de familia y Empleados a fin de prepararse a nivel interno para afrontar las amenazas propias en el ámbito locativo o externo, sea natural o entrópico.|
: {.responsive}
