# Información General IEMS

<div class="table-responsive">
<table>
<colgroup>
<col />
<col />
<col />
</colgroup>
<tbody>
<tr>
<td colspan="3"><em><strong>IDENTIFICACIÓN DEL ESTABLECIMIENTO EDUCATIVO</strong></em></td>
</tr>
<tr>
<td colspan="2">Nombre de la Institución</td>
<td>INSTITUCIÓN EDUCATIVA MARISCAL SUCRE</td>
</tr>
<tr>
<td colspan="2">Carácter</td>
<td>Oficial</td>
</tr>
<tr>
<td colspan="2">Zona</td>
<td>Urbana</td>
</tr>
<tr>
<td colspan="2">Dirección, Teléfono, E-mail</td>
<td>Carrera 16 No. 63-15 Urbanización La Toscana. Tel. 8900119 <a href="mailto:iemariscalsucre@semmanizales.edu.co">iemariscalsucre@semmanizales.edu.co</a></td>
</tr>
<tr>
<td colspan="2">Comuna, Núcleo o Corregimiento</td>
<td>Comuna Eco turística Cerro de Oro </td>
</tr>
<tr>
<td colspan="2">Nombre e Identificación del Rector</td>
<td>OSCAR IVAN FRANCO GUTIERREZ.</td>
</tr>
<tr>
<td colspan="2">Dirección, Teléfono y correo electrónico del Rector</td>
<td><a href="mailto:oifg1028@hotmail.com"><u>oifg1028@hotmail.com</u></a></td>
</tr>
<tr>
<td colspan="2">Fecha de Fundación</td>
<td>10 de Febrero de 1969 </td>
</tr>
<tr>
<td colspan="2">Última Resolución de Aprobación de Estudios</td>
<td><p>Res. No. 1470 de noviembre 16 de 2011</p>
<p> </p></td>
</tr>
<tr>
<td colspan="2">Código Dane</td>
<td>DANE: 117001002303 NIT: 890802079-2</td>
</tr>
<tr>
<td colspan="2">Código ICFES</td>
<td>031526</td>
</tr>
<tr>
<td colspan="2">Tipo de Institución (Académica, Técnica, Normal)</td>
<td>Académica</td>
</tr>
<tr>
<td colspan="2">Título que otorga</td>
<td>Bachiller Académico </td>
</tr>
<tr>
<td colspan="2">Calendario</td>
<td>A </td>
</tr>
<tr>
<td colspan="2">Grado de Inclusión, el índice de inclusión obtenido según encuesta del año 2015 es de 2.78; 2019 fue 2.94 y el 2024 de 3.24</td>
<td>Se realizan acciones organizadas en las áreas de gestión, las cuales son conocidas por la mayoría de los integrantes de la comunidad educativa)</td>
</tr>
<tr>
<td colspan="2">Niveles que ofrece</td>
<td>Transición, Básica Primaria, Básica Secundaria, Media Académica y educación de Adultos por CLEIs</td>
</tr>
<tr>
<td colspan="2">Sedes: Nombres y Direcciones</td>
<td><p>Sede Principal: Mariscal Sucre. Carrera 16 No. 63-15 Urbanización La Toscana;</p>
<p>Sede C: John F. Kennedy, Calle 62 No. 11B 45</p>
<p>Sede D: Ricardo Flórez, Calle 63 No. 13-30 </p></td>
</tr>
<tr>
<td colspan="2">Número de Grupos por Niveles</td>
<td><p>Preescolar: 1</p>
<p>Básica Primaria:9</p>
<p>Básica Secundaria: 6</p>
<p>Modelos Flexibles: 7</p>
<p>Media Académica: 5</p>
<p>Total: 28 grupos</p></td>
</tr>
<tr>
<td colspan="2">Matrícula actual por niveles:</td>
<td><p>Preescolar:  23</p>
<p>Primaria: 176</p>
<p>Primaria y secundaria Geempa: 114</p>
<p>Secundaria: 156</p>
<p>Caminando en Secundaria:44</p>
<p>Media: 134</p>
<p>Total: 647</p></td>
</tr>
<tr>
<td colspan="2">Número de Docentes por Niveles:</td>
<td><p>Preescolar: 2</p>
<p>Didácticas Flexibles: 6</p>
<p>Básica Primaria: 8</p>
<p>Básica Secundaria y Media: 21</p>
<p>Total: 34</p></td>
</tr>
<tr>
<td colspan="2">Número de Directivos</td>
<td><p>Rector: 1</p>
<p>Coordinadores: 1 </p></td>
</tr>
<tr>
<td colspan="2">Número de Administrativos y de Servicios Generales</td>
<td>1 secretaria, 1 tesorera, 1 servicios generales.</td>
</tr>
<tr>
<td rowspan="3">Jornadas y Horarios:</td>
<td>Mañana:</td>
<td>7:00 am a 1:00 pm. Sede Principal</td>
</tr>
<tr>
<td>Mañana: caminando la secundaria</td>
<td>7.== AM – 1:00 PM</td>
</tr>
<tr>
<td>Unica:</td>
<td><p>7:00 – 12:30 Transición </p>
<p>7:00 a.m. a 2:00 primaria</p>
<p>7:00 am – 2:30 secundaria (6°, 7°,8° y 9°)</p></td>
</tr>
<tr>
<td colspan="2">Certificado de Bomberos</td>
<td>Nº 4332 de junio 23 de 2010</td>
</tr>
<tr>
<td colspan="2">Acuerdo del Consejo Directivo de adopción del PEI</td>
<td>006 de junio 2de 2026</td>
</tr>
<tr>
<td colspan="2">Indice de inclusión</td>
<td>3.24</td>
</tr>
<tr>
<td colspan="2">Licencia de funcionamiento</td>
<td>Resolución Nº 1740 de noviembre 16 de 2011</td>
</tr>
</tbody>
</table>
</div>
: Información General IEMS {.responsive #tbl-informacion-general}
